# Generated by Django 3.2 on 2021-10-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=50)),
                ('completed', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField()),
            ],
        ),
    ]
